### ISSUE TITLE
[SUGGESTION] Automatic padding over pre-set one

### ISSUE THREAD

**Issue by theAbdoSabbagh** [PrivatePandaCO/pyloggor#1]
Make the padding (amount of spaces after text such as topic and message) custom, so it's like 1-2 space(s) after the text, that way it doesn't unnecessarily occupy too much space in the terminal as it sometimes results in having multiple lines being used, which is just ugly

**Comment by ThePrivatePanda** [comment]
You can configure that by passing in `topic_beauty_space`, `file_beauty_space`, `level_beauty_space` while instantizing the logger.
Read Initialization -> point 4 [here](https://github.com/PrivatePandaCO/PyLoggor#Config) for a more detailed explanation.

**Comment by theAbdoSabbagh** [comment]
Is it not possible to make it custom? like adding a single space after the text, instead of the user having to configure it manually.

**Comment by ThePrivatePanda** [comment]
I'm not sure what you mean, Topic and File space adjusments defaults to 30 and 10 for level, they are not necessary parameters.

Do you mean an option that this adjustment doesn't occur at all?

**Comment by theAbdoSabbagh** [comment]
nvm, I just did what you said and set the params manually whilst initializing the PyLoggor class, works good enough
